### ISSUE TITLE
Rango vocal

### ISSUE THREAD

**Issue by R2Damacena** [isra00/neo-transposer#202]
Hola  @isra00, soy parte de las comunidades del Camino Neocatecumenal en Brasil. Me gustaría saber cómo funciona el rango vocal, porque sólo llega hasta B3. ¿Cómo funciona para las mujeres que llegan a notas más altas? Porque es más fácil averiguar el rango vocal desde el piano, pero para mí es extraño añadirlo a la aplicación porque mi rango es C2 - G4. 

En la aplicación, la parte más grave sólo va de C1 - B1. ¿No tendría que haber octavas también? Sobre todo para las mujeres que no llegan a esas notas graves.

Gracias de antemano por desarrollar esta aplicación, que es de gran ayuda para los salmistas de todo el mundo.

_Espero que lo entiendas, he usado un traductor para traducir del portugués al español._

**Comment by isra00** [comment]
Hola Arthur! Para el propósito de Neo-Transposer, las octavas en el rango vocal absolutas, sino relativas. Por ejemplo, para una mujer con rango D3-D5, en Neo-Transposer puedes poner D2-D4. Es lo mismo porque se trata de transponer acordes, y los acordes no saben de octavas, sino que funcionan cíclicamente.

De hecho, cuando configuras manualmente el rango en Neo-Transposer ya no se eligen rangos exactos, sino distancia a partir de una nota base:

![IMG_20240411_010520](https://github.com/isra00/neo-transposer/assets/94328/33fa6322-b5da-47aa-a9e6-579a1a30987c)

**Comment by R2Damacena** [comment]
Entonces, para una mujer con un registro vocal de D3 para la nota más grave alcanzada y D5 para la nota más aguda alcanzada, ¿qué pongo manualmente? ¿Así?:

![image](https://github.com/isra00/neo-transposer/assets/63689000/63b9e79c-9a6a-44e3-8e98-6c1fddb715b8)

Pero lo que me deja en duda es el hecho de que las notas más graves sólo van de C1 -> B1.
![image](https://github.com/isra00/neo-transposer/assets/63689000/f4a1ae4a-a691-45a7-965b-642060e5fb78)

Y para los agudos sólo hasta B3:
![image](https://github.com/isra00/neo-transposer/assets/63689000/795e883a-0ff8-48f2-8483-a1b72d74d0a6)


Disculpe cualquier cosa, pero gracias de antemano por su respuesta. Quizás no entendí lo que dijo antes. ¡Paz!

**Comment by isra00** [comment]
Correcto. D3 a D5 es como decir D a D + 2 octavas de la nota más grave.
